name: Vercel Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Detect Site Folder
        id: detect
        run: |
          folder=$(find Sites -maxdepth 1 -mindepth 1 -type d | head -n 1)
          echo "Detected folder: $folder"
          echo "site_folder=$folder" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ${{ steps.detect.outputs.site_folder }}
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Info
        working-directory: ${{ steps.detect.outputs.site_folder }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel pull --yes --environment=preview

      - name: Build Project
        working-directory: ${{ steps.detect.outputs.site_folder }}
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        id: deploy
        working-directory: ${{ steps.detect.outputs.site_folder }}
        run: |
          url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "preview_url=$url" >> $GITHUB_OUTPUT

      - name: Comment Preview URL on PR
        uses: actions/github-script@v7
        with:
          script: |
            const url = "${{ steps.deploy.outputs.preview_url }}";
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ Preview deployed for \`${{ steps.detect.outputs.site_folder }}\`:\n\n🔗 [View Preview](${url})`
            });
