name: Deploy PR Site to Vercel

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Get changed folder
        id: detect
        run: |
          folder=$(git diff --name-only origin/main...HEAD | grep '^Sites/' | cut -d/ -f2 | head -n1)
          echo "Detected site folder: $folder"
          echo "folder=$folder" >> $GITHUB_OUTPUT

      - name: Deploy site to Vercel
        id: deploy
        run: |
          cd Sites/${{ steps.detect.outputs.folder }}
          url=$(vercel --yes --token=ipvzJHgypRYHHIwH8d7lbyBN)
          echo "preview_url=$url" >> $GITHUB_OUTPUT

      - name: Comment PR with preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview-link
          message: |
            🚀 Preview URL for **${{ steps.detect.outputs.folder }}**:  
            👉 ${{ steps.deploy.outputs.preview_url }}
