name: Deploy Vercel Preview on PR

on:
  pull_request:
    paths:
      - 'Sites/**'
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect folder inside /Sites/
        id: detect
        run: |
          git fetch origin main
          folder=$(git diff --name-only origin/main...HEAD | grep '^Sites/' | cut -d/ -f2 | sort | uniq | head -n 1)
          echo "Detected folder: $folder"
          echo "folder=$folder" >> $GITHUB_OUTPUT

      - name: Fail if no site folder found
        run: |
          if [ -z "${{ steps.detect.outputs.folder }}" ]; then
            echo "❌ No folder detected inside /Sites/."
            exit 1
          fi

      - name: Set working directory variable
        run: echo "SITE_DIR=Sites/${{ steps.detect.outputs.folder }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ${{ env.SITE_DIR }}
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel environment settings
        working-directory: ${{ env.SITE_DIR }}
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build the site
        working-directory: ${{ env.SITE_DIR }}
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        id: vercel_deploy
        working-directory: ${{ env.SITE_DIR }}
        run: |
          url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Comment preview URL on PR
        uses: actions/github-script@v7
        with:
          script: |
            const url = "${{ steps.vercel_deploy.outputs.url }}";
            const folder = "${{ steps.detect.outputs.folder }}";
            const body = `✅ **Preview deployed for** \`/Sites/${folder}\`:\n\n🔗 [View Preview](${url})`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });
