name: Vercel Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Detect Site Folder
        id: detect
        run: |
          folder=$(find Sites -mindepth 1 -maxdepth 1 -type d | head -n 1)
          echo "Detected folder: $folder"
          echo "site_folder=$folder" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ${{ steps.detect.outputs.site_folder }}
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Info
        working-directory: ${{ steps.detect.outputs.site_folder }}
        run: |
          vercel pull --yes --environment=preview \
            --token=ipvzJHgypRYHHIwH8d7lbyBN \
            --org-id=${{ secrets.VERCEL_ORG_ID }} \
            --project-id=${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build with Vercel
        working-directory: ${{ steps.detect.outputs.site_folder }}
        run: vercel build --token=ipvzJHgypRYHHIwH8d7lbyBN

      - name: Deploy to Vercel (Preview)
        id: deploy
        working-directory: ${{ steps.detect.outputs.site_folder }}
        run: |
          url=$(vercel deploy --prebuilt --token=ipvzJHgypRYHHIwH8d7lbyBN)
          echo "preview_url=$url" >> $GITHUB_OUTPUT

      - name: Comment Preview URL on PR
        uses: actions/github-script@v7
        with:
          script: |
            const url = "${{ steps.deploy.outputs.preview_url }}";
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ **Vercel Preview Deployed** for \`${{ steps.detect.outputs.site_folder }}\`:\n\n🔗 [View Preview Deployment](${url})`
            });
